version: "3.10"

services:
  web_1:
    container_name: fast_api_mysql
    build:
      context: ./main
      dockerfile: Dockerfile.server
      args:
        DB: mysql
    command: bash -c './wait-for-it.sh --timeout=0 db_1:3306 && python main.py'
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@db_1:3306/practice
      - PORT=8080
    depends_on:
      - db_1
  db_1:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root

  web_2:
    container_name: fast_api_postgresql
    build:
      context: ./main
      dockerfile: Dockerfile.server
      args:
        DB: postgresql
    command: bash -c './wait-for-it.sh --timeout=0 db_2:5432 && python main.py'
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://root:root@db_2:5432/practice
      - PORT=8000
    depends_on:
      - db_2
  db_2:
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=practice

  script:
    container_name: script
    build:
      context: ./main
      dockerfile: Dockerfile.script
    command: bash -c 'ls && ./wait-for-it.sh --timeout=0 web_1:8080 && ./wait-for-it.sh --timeout=0 web_2:8000 && python main.py'
    volumes:
      - ./main/script/results:/app/results

volumes:
    mysql:
    mysql_config:
    postgres_data: